version: 2.1

orbs:
  kaocha: lambdaisland/kaocha@0.0.2
  clojure: lambdaisland/clojure@0.0.6

commands:
  checkout_and_run:
    parameters:
      clojure_version:
        type: string
    steps:
      - checkout
      - run: npm install ws
      - run: ulimit -c unlimited
      - clojure/with_cache:
          cache_version: << parameters.clojure_version >>
          steps:
            - kaocha/execute:
                args: "--reporter documentation --plugin cloverage --codecov"
                clojure-args: "-J-XX:+UseSerialGC"
                clojure_version: << parameters.clojure_version >>
                aliases: ":dev:test:test-check:cljs:instaparse:malli"
            - run:
                command: |
                  mkdir -p /tmp/core_dumps
                  cp core.* /tmp/core_dumps
                when: on_fail
      - store_artifacts:
          path: /tmp/core_dumps
      - kaocha/upload_codecov

jobs:
  java-15-clojure-1_10:
    executor: clojure/openjdk15
    steps: [{checkout_and_run: {clojure_version: "1.10.2"}}]

  java-15-clojure-1_9:
    executor: clojure/openjdk15
    steps: [{checkout_and_run: {clojure_version: "1.9.0"}}]
    
  java-11-clojure-1_10:
    executor: clojure/openjdk11
    steps: [{checkout_and_run: {clojure_version: "1.10.2"}}]

  java-11-clojure-1_9:
    executor: clojure/openjdk11
    steps: [{checkout_and_run: {clojure_version: "1.9.0"}}]

  java-9-clojure-1_10:
    executor: clojure/openjdk9
    steps: [{checkout_and_run: {clojure_version: "1.10.2"}}]

  java-9-clojure-1_9:
    executor: clojure/openjdk9
    steps: [{checkout_and_run: {clojure_version: "1.9.0"}}]

  java-8-clojure-1_10:
    executor: clojure/openjdk8
    steps: [{checkout_and_run: {clojure_version: "1.10.2"}}]

  java-8-clojure-1_9:
    executor: clojure/openjdk8
    steps: [{checkout_and_run: {clojure_version: "1.9.0"}}]

workflows:
  kaocha_test:
    jobs:
      - java-15-clojure-1_10
      - java-15-clojure-1_9
      - java-11-clojure-1_10
      - java-11-clojure-1_9
      - java-9-clojure-1_10
      - java-9-clojure-1_9
      - java-8-clojure-1_10
      - java-8-clojure-1_9
